### ISSUE TITLE
VimCom Failed Installation on Mac OS Yosemite with Homebrew R

### ISSUE THREAD

**Issue by tinyheero** [jalvesaq/VimCom#27] opened 2015-09-07 20:43 UTC
Hi,

If homebrew is used to install R (v3.2.2), the `install.packages` command fails on Mac OS Yosemite (v 10.10.5):

```r
install.packages("vimcom_1.2-6.tar.gz", repos = NULL, type = "source", configure.args = "--enable-clientserver")
```

It complains about missing X11/Xlib.h. I think the issue lies in when the Xquartz is installed the X11 libraries and headers are placed into /opt/X11. As my R is installed into `/usr/local/Cellar/R/3.2.2` it doesn't know where to look for the X11 (even though I installed R through homebrew with the `--with-x11` parameter). 

I got around the `install.packages` issue by setting the `--x-includes` and `--x-libraries` parameters such that they explicitly indicate where the X11 libraries and headers are:

```r
install.packages("vimcom_1.2-6.tar.gz", type = "source", configure.args="--enable-clientserver, --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib", repos = NULL)
```

Fong

**Comment by jalvesaq** [comment] 2015-09-08 19:00
Thanks for your feedback! It will be useful for others trying to install the package in similar circumstances.

**Comment by scottstanfield** [comment] 2016-01-22 17:48
This thing is a monster to install. I'm on El Capitan trying to get `vim` (terminal, not MacVim), `tmux` and `R` to play nice using `VimCom`, `jcfaria/Vim-R-plugin` and `jalvesaq/R-vim-runtime` to work. I have X11 installed (not sure if I need it since I'm in the terminal). 

If I do get it all working by some miracle, I'll repost the steps while it's still fresh in my head.

Really motivated to *not* use `RStudio.app`

**Comment by jalvesaq** [comment] 2016-01-22 17:58
Why not switch to Neovim? Please, read the last comments of https://github.com/jalvesaq/VimCom/issues/28

**Comment by scottstanfield** [comment] 2016-01-22 18:12
Thanks @jalvesaq. It's not an option for me at this point. I have a lot invested in my .vimrc configuration that's working great. 

But good news: I just got all this working. So I plan on posting a gist to this wiki with the steps to make it work. It's frankly amazing that it works. Thanks for this. Post coming soon, before I forget :)

**Comment by jalvesaq** [comment] 2016-01-22 18:48
I use the same vimrc for Vim and Neovim, but perhaps my vimrc is much simpler than yours. At this moment, I have only two conditions in my vimrc that change the editor's behavior depending on whether I am using Vim or Neovim:

```vim
if has("nvim")
    Plug 'Shougo/deoplete.nvim'
    Plug 'Shougo/neocomplete'
    Plug 'Shougo/neosnippet'
    Plug 'Shougo/neosnippet-snippets'
    Plug 'jalvesaq/Nvim-R'
    Plug 'jalvesaq/R-Vim-runtime'
else
    Plug 'jcfaria/Vim-R-plugin'
endif
```

and

```vim
if $HAS_256_COLORS != "yes" && has("nvim")
    colorscheme default
else
    colorscheme southernlights
endif
```

This second condition is to get better colors in LInux console (which I almost never use).

However, if you use any plugin that depends on Vim's 'clientserver' feature (like SyncTeX support for LaTeX), it will not work yet, unless the author has adapted the plugin to Neovim.

**Comment by scottstanfield** [comment] 2016-01-22 19:18
I'm afraid I have 555 lines in my `.vimrc`:
https://github.com/scottstanfield/dotfiles/blob/master/vimrc

I'm looking forward to an upgrade, but I think it'll take the better part of a weekend to do it!

BTW, I'm reproducing the vim + tmux + vimcom configuration on a clean Mac and noting the steps.

**Comment by jalvesaq** [comment] 2016-01-22 20:29
I am sure that you would have to make some code in your vimrc conditional. If you want to try Neovim you may want to see:
https://neovim.io/doc/user/nvim_from_vim.html
https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal
https://github.com/benekastah/neomake (syntastic replacement)

And also:
https://github.com/neovim/neovim/wiki/Related-projects

**Comment by jalvesaq** [comment] 2016-03-02 13:12
This might be fixed by (although not tested on Mac OS X):
https://github.com/jcfaria/Vim-R-plugin/tree/jobchannel
https://github.com/jalvesaq/VimCom/tree/jobchannel

**Comment by jalvesaq** [comment] 2016-03-04 12:29
This issue should be fixed now.

**Closed** 2016-03-16 11:57 UTC
Labels: solution: Neovim
