### ISSUE TITLE
Missing environment variable: "VIMR_COMPLDIR"

### ISSUE THREAD

**Issue by xguardi** [jalvesaq/VimCom#34] opened 2016-03-09 17:56 UTC
I'm using the R-vim-plugin on a Mac, with terminal vim (installed from brew) and tmux. I've just installed vimcom from R using the devtools and everything went fine. But when I launch the R session it gives me the warning:

Warning message:
In fun(libname, pkgname) : Missing environment variable: "VIMR_COMPLDIR"

Has vimcom succesfully launched? How can I be sure?
Thanks and congrats for this awesome plugin!!

Xavi.

**Comment by jalvesaq** [comment] 2016-03-09 18:12
Perhaps your Vim-R-plugin is outdated. Since you are using the development version of vimcom, you also have to use the development version of Vim-R-plugin: https://github.com/jcfaria/Vim-R-plugin

But you may also want to try Neovim + Nvim-R + nvimcom to run R in a neovim built-in terminal.

**Comment by xguardi** [comment] 2016-03-10 10:11
Thanks, I've just did. I've checked that
1. Vim was compiled with +channel, +conceal
2. Vimcom was installed as install.packages("path/to/VimCom", type = "source", repos = NULL,
                  configure.args = "--enable-clientserver")
And when launch the plugin from vim I get that message that vimcom is loaded. 
So far so good.
However whenever I try to autocomplete I get this:

Error detected while processing function rcomplete#CompleteR[14]..BuildROmniList[13]..SendToVimCom:
line    6:
E121: Undefined variable: g:rplugin_channel
Press ENTER or type command to continue

**Comment by jalvesaq** [comment] 2016-03-10 11:11
The configure argument `--enable-clientserver` is no longer used. But it is harmless on Linux.

Vim also needs the +job feature. I'm going to add this to the documentation.

To be sure that the new version of vimcom was really installed, you could uninstall it before trying to install again. If there are errors during vimcom compilation, you should report them because I don't have access to any Mac OS X to make tests.

**Comment by xguardi** [comment] 2016-03-10 23:46
Still getting the same error. When I launch the plugin I get:

Could not find "/Users/Xavier/Library/R/3.2/library/vimcom/bin/vclientserver". [Press <Enter> to continue]

Summary of my installation:
1. Mac OSX 10.10.5 Yosemite
2. vim version 7.4.1525. Installed with brew +job, +channel, +conceal
3. Vim-R-plugin installed from https://github.com/jcfaria/Vim-R-plugin (Vundle)
4. vimcom installed as devtools::install_github("jalvesaq/VimCom")

So everything as fresh as possible :-)
Any ideas about how I could gather more info?

Cheers!

Xavi.

**Comment by jalvesaq** [comment] 2016-03-11 00:21
The current development version of the Vim-R-plugin defines the environment variable VIMR_COMPLDIR while previous versions defined VIMRPLUGIN_COMPLDIR. So, it looks like the plugin that is running is older than it should be. Do you have two versions of the plugin installed? That is, did you install a released version using the Vimball and then installed the development version using Vundle?

**Comment by xguardi** [comment] 2016-03-11 14:24
Nope. I checked the source code for common_global.vim and I can see the VIMR_COMPLDIR variable being used, so I'm pretty sure it must be the last version. Maybe I need to work with another branch rather than the master?

**Comment by xguardi** [comment] 2016-03-11 14:42
I was checking the vimcom package path (R/3.2/library/vimcom) and I see no bin folder.

**Comment by jalvesaq** [comment] 2016-03-11 15:48
The bin directory is created on both Linux and Windows. I don't know what's going wrong there...

The current development version of Nvim-R supports Vim, and the next release of Vim-R-plugin + vimcom will be the last one because I will only maintain Nvim-R + nvimcom. If you want to try them, you will also need the development version of syntax/r.vim. So, you should install:

https://github.com/jalvesaq/R-Vim-runtime
https://github.com/jalvesaq/Nvim-R
https://github.com/jalvesaq/nvimcom

I prefer to use Neovim because I like to run R in the built-in terminal.

**Comment by zeloff** [comment] 2016-03-15 22:32
FWIW I'm also getting the `Could not find "[...]/vimcom/bin/vclientserver"`error on OpenBSD since 1.2.8 (I think, but I'm not entirely sure that's the right version). The `bin` folder definitely isn't being created...

Sad to see you drop vim support, but I understand that supporting both worlds quickly becomes unfeasible and/or limiting.

**Comment by zeloff** [comment] 2016-03-15 23:00
I think that since c4ba87ad74aaac9cff3129e741f6d2226fbcd2ba changed the build process, `make` is never run inside `src/apps`, so `vclientserver` is never compiled, and consequently never installed into `bin/`.

`src/Makevars.win` makes sure this happens with the `vimapps:` target, but there is no such thing for other platforms, hence the missing binary.

**Comment by jalvesaq** [comment] 2016-03-15 23:24
@zeloff Please, try Vim + Nvim-R.
You don't have to install Neovim because Nvim-R now supports both Vim and Neovim.
If you only use released versions, than, please downgrade Vim-R-plugin and wait until the next version of Nvim-R is released.

It takes too much time to maintain both Vim-R-plugin and Nvim-R. So, now that Vim has the +job and +channel feature, Nvim-R supports it too. I was waiting until the Cream project released Vim >= 7.4.1553 for Windows because some people may have difficult to compile Vim on Windows. But I am going to announce that the development of Vim-R-plugin and vimcom continues on Nvim-R.

**Comment by zeloff** [comment] 2016-03-15 23:33
Sorry about that. I didn't read your comment carefully enough and missed "The current development version of Nvim-R supports Vim". Will move. Many thanks

**Comment by jalvesaq** [comment] 2016-03-15 23:45
The Makefile rule on Unix to build `vclientserver` (vimcom) and `nclientserver` (nvimcom) is:

```Makefile
vclientserver: vclientserver.c
	$(CC) $(CFLAGS) vclientserver.c -o vclientserver
```

The only difference is the prefix "v" for vimcom and "n" for nvimcom.
Perhaps this does not work on OpenBSD and Mac OS X.
Could you, please, tell me whether this works or not:

```Makefile
nclientserver: nclientserver.o
        $(CC) $(CFLAGS) nclientserver.o -o nclientserver

nclientserver.o: nclientserver.c
        $(CC) $(CFLAGS) nclientserver.c -c -o nclientserver.o
```

**Comment by zeloff** [comment] 2016-03-15 23:51
The problem isn't on `apps/Makefile`, that works ok, as I tested by running it manually (see my long comment above). The thing is that `(cd apps & make)` never happens. On Windows, `Makevars.win` is used, and since it has a `vimapps:` target, that `Makefile` is ran. But on Unix, there is no such file since c4ba87ad74aaac9cff3129e741f6d2226fbcd2ba removed `src/Makevars.in`

**Comment by jalvesaq** [comment] 2016-03-16 00:15
The target on Windows is intended to build a dll useful only for Windows (used to copy the command into clipboard, raise Rgui window, paste the command, and raise Gvim window).

Makevar.in, configure, etc were necessary because X11 libraries were used and I needed configure and their friends to discover where X11 libraries headers were and how to link to the library etc.

I don't know how to solve the problem on OpenBSD because src/Makevars works on Linux.

**Comment by jalvesaq** [comment] 2016-03-16 00:28
Note that Makevars is used on Unix and Makevars.win on Windows.

**Comment by jalvesaq** [comment] 2016-03-16 10:02
Acording to R documentation, *Writing R Extensions*:

> Some `make` programs require makefiles to have a complete final line, including a newline.

**Comment by jalvesaq** [comment] 2016-03-16 10:09
I just noticed that Makevars was included in .gitignore. It existed in my local directory, but not in github repository. The bug should be fixed now.

**Comment by zeloff** [comment] 2016-03-16 10:57
Yep, ac5df6bff9431a4d4e112580b4e6b1d67607a34a solves this issue for me. Many thanks

**Closed** 2016-03-16 11:56 UTC
